version: 2
builds:
  - goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    main: ./cmd/pgtestserver
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
publishers:
  - name: gh
    env:
      - GITHUB_TOKEN="{{ .Env.GITHUB_TOKEN }}"
    cmd: env && bin/gh release upload --clobber {{ .Tag }} dist/{{ .ArtifactName }}
