#!/bin/sh
#/ script/pgdevserver builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/pgdevserver ./cmd/pgdevserver

exec bin/pgdevserver "$@"
