#!/bin/sh
#/ script/pgtestserver builds and runs the project with the given arguments.

set -e

CDPATH="" cd -- "$(dirname -- "$0")/.."

go build -o bin/pgtestserver ./cmd/pgtestserver

exec bin/pgtestserver "$@"
